IL17_week_one_in_vivo <- read_csv("~/Dropbox/Tulane/You_lab/Metastasis_project/MPC3/Experiments/Orthotopic_luciferase_imaging/IL17_metastasis_study/DMC20170925101238/IL17_week_one_in_vivo.csv")
con_1_week_mean_lum <- mean(IL17_week_one_in_vivo$`Avg Radiance [p/s/cm_/sr]`[1:5]), con_1_week_se <- sd(IL17_week_one_in_vivo$`Avg Radiance [p/s/cm_/sr]`[1:5])/sqrt(5)
con_1_week_mean_lum <- mean(IL17_week_one_in_vivo$`Avg Radiance [p/s/cm_/sr]`[1:5]); con_1_week_se <- sd(IL17_week_one_in_vivo$`Avg Radiance [p/s/cm_/sr]`[1:5])/sqrt(5)
log_con_1_week_mean_lum <- log(con_1_week_mean_lum); log_con_1_week_mean_lum_se <- log(con_1_week_se)
log_IL17_1_week_mean_lum <- mean(IL17_week_one_in_vivo$`Avg Radiance [p/s/cm_/sr]`[6:13]); log_IL17_1_week_se <- sd(IL17_week_one_in_vivo$`Avg Radiance [p/s/cm_/sr]`[6:13])/sqrt(8)
log_IL17_1_week_mean_lum <- log((mean(IL17_week_one_in_vivo$`Avg Radiance [p/s/cm_/sr]`[6:13])); log_IL17_1_week_se <- log(sd(IL17_week_one_in_vivo$`Avg Radiance [p/s/cm_/sr]`[6:13]))/sqrt(8)
log_IL17_1_week_mean_lum <- log((mean(IL17_week_one_in_vivo$`Avg Radiance [p/s/cm_/sr]`[6:13]))); log_IL17_1_week_se <- log(sd(IL17_week_one_in_vivo$`Avg Radiance [p/s/cm_/sr]`[6:13]))/sqrt(8)
primary_tumor_growth <- data.frame(days_post_inoculation=c(7,7),mean_tumor_lum=c(log_con_1_week_mean_lum,log_IL17_1_week_mean_lum),se=c(log_con_1_week_mean_lum_se,log_IL17_1_week_se),group=rep(c("con", "IL17"),each=1)
install.packages("ggplot2")
p <- ggplot(data = primary_tumor_growth,mapping = aes(x=primary_tumor_growth$days_post_inoculation,y=primary_tumor_growth$mean_tumor_lum,group=primary_tumor_growth$group,color=group))
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
p+geom_col(position = position_dodge(width = 1))+theme_classic()+geom_errorbar(aes(ymax=primary_tumor_growth$mean_tumor_lum+primary_tumor_growth$se,ymin=primary_tumor_growth$mean_tumor_lum+primary_tumor_growth$se),position = position_dodge(width = 1))+xlab("Days Post Inoculation")+ylab("Log Mean Tumor Luminescence (p/s/cm2/sr)")+scale_color_manual(values = cbbPalette)
